version: '3.8'

services:
  traefik:
    image: traefik:v2.5
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"

  react-app:
    build: .
    container_name: react-app
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.react-app.rule=Host(`pierrezhou.dev`)"
      - "traefik.http.routers.react-app.entrypoints=websecure"
    networks:
      - default
