version: '3.8'

services:
  traefik:
    image: traefik:v2.6
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.pierrezhou.acme.tlschallenge=true"
      - "--certificatesresolvers.pierrezhou.acme.email=pierezhoou@gmail.com"
      - "--certificatesresolvers.pierrezhou.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./letsencrypt:/letsencrypt"
    restart: always

  app:
    build: .
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.app.tls.certresolver=pierrezhou"
      - "traefik.http.routers.app.rule=Host(`pierrezhou.dev`)"
      - "traefik.http.routers.app.entrypoints=web,websecure"
      - "traefik.http.routers.app.tls=true"
      - "traefik.http.services.app.loadbalancer.server.port=4173"
    volumes:
      - .:/app
